### ISSUE TITLE
Bad references for diou and ciou

### ISSUE THREAD

**Issue by tteresi7** [GerardMaggiolino/Deep-OC-SORT#11]
In the `association.py` files in each of the trackers, the diou and ciou references the giou paper https://arxiv.org/pdf/1902.09630.pdf.  These should be https://arxiv.org/pdf/1911.08287.pdf.

**Comment by GerardMaggiolino** [comment]
Sorry, the code is definitely a little janky. However, we only use the standard IoU metric for all results published.
