### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by Zhanlangmc** [GerardMaggiolino/Deep-OC-SORT#13]
Sorry to bother you, but I uploaded my own dataset which has the same format as MOT17 and run  '__python main.py --exp_name baseline --post --emb_off --cmc_off --aw_off --new_kf_off --grid_off --dataset mot17' as guided. But it seems like something is wrong because it takes 0 seconds to load the annotations and the result file is empty.
![image](https://user-images.githubusercontent.com/128991008/234907069-9d4d2e22-b08e-4b13-9e3d-7ee61a1e6957.png)
My dataset is structured like this: 
![image](https://user-images.githubusercontent.com/128991008/234907340-5e1e019f-fae5-48c3-a6d1-72c2d0c0dc3e.png)
Thank you for your time.

**Comment by GerardMaggiolino** [comment]
Please see the `convert` files which load MOT annotations and convert them to COCO with metadata about file names. If you just have a flat folder of images, it should be pretty straightforward to hack the `dataset.py` file to load these without annotations.
