### ISSUE TITLE
Question about the Strongsort++ results on the Dancetrack dataset

### ISSUE THREAD

**Issue by Sheldon-Zheng** [GerardMaggiolino/Deep-OC-SORT#15]
I used the original code of Strongsort++ and the YOLOX and SBS weights provided in your project but have yet to get the satisfying result mentioned in your paper. Could you please provide more details about changes or parameter settings to this algorithm?

**Comment by GerardMaggiolino** [comment]
The StrongSORT++ results were obtained from their publication here directly, we did not attempt to reproduce their results:  https://arxiv.org/pdf/2202.13514.pdf

**Comment by Sheldon-Zheng** [comment]
Thank you for your prompt reply！
