### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by xqoby** [GerardMaggiolino/Deep-OC-SORT#16]
I want to ask you a question. I got an error while running ' python3 main.py --exp_name best_paper_ablations --post --grid_off --new_kf_off --dataset mot17 --w_assoc_emb 0.75 --aw_param 0.5' 
The error information is as follows:

![1684132788(1)](https://github.com/GerardMaggiolino/Deep-OC-SORT/assets/133632592/2f97225b-52b3-43c0-80e2-c9c739e5f47a)

**Comment by GerardMaggiolino** [comment]
Were you able to resolve this? It's possible that you had previously cached embeddings without `--grid_off`. Clearing the embedding cache should fix this.
