### ISSUE TITLE
ABOUT REID VERSION

### ISSUE THREAD

**Issue by gw0522** [GerardMaggiolino/Deep-OC-SORT#17]
As for the reid module in the paper, may I ask which version of reid is used here? Is it proposed by the article BoT: Bag of Tricks and A Strong Baseline for Deep Person Re-identification?

**Comment by GerardMaggiolino** [comment]
We use the config here, which is the Fast-ReID SBS ResNet50 model:
https://github.com/GerardMaggiolino/Deep-OC-SORT/blob/main/external/fast_reid/configs/Base-SBS.yml

You can refer to the Fast-ReID project: https://github.com/JDAI-CV/fast-reid/blob/master/MODEL_ZOO.md

It's a slightly stronger version of the original BoT, which is the same model BoT-SORT used.
