### ISSUE TITLE
Dynamic Appearance

### ISSUE THREAD

**Issue by flag16** [GerardMaggiolino/Deep-OC-SORT#18]
Thank you for your great work !
I can't find Dynamic Appearance in the code, could you tell me exactly where it is implemented?

**Comment by GerardMaggiolino** [comment]
It's just three lines of code here: 
 https://github.com/GerardMaggiolino/Deep-OC-SORT/blob/6bb51d027b137233f5c520b6fcc4f2ae387a6ba9/trackers/integrated_ocsort_embedding/ocsort.py#L420

**Comment by flag16** [comment]
Thank you for your answer.
