### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YanhuiS** [GerardMaggiolino/Deep-OC-SORT#4]
emb_cost = None if (trk_embs.shape[0] == 0 or det_embs.shape[0] == 0) else det_embs @ trk_embs.T    
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 512)

**Comment by GerardMaggiolino** [comment]
Thanks for your interest! Have you ensured you’re running with the —grid_off flag? I’ll change that to be the default.

**Comment by YanhuiS** [comment]
python3 main.py --exp_name 1 --post --grid_off --new_kf_off --dataset mot17 --w_assoc_emb 0.75 --aw_param 0.5. when I run DeepOCSORT on MOT17, I met this question.
