### ISSUE TITLE
cmc_files

### ISSUE THREAD

**Issue by upperblacksmith** [GerardMaggiolino/Deep-OC-SORT#5]
hello,its a nice work. i have some questions about the paper. 
1.how did you get cmc files(camera motion compensation, its located in ./cache/cmc_files/***).
2.if i want use it in my custom data or custom program,how should i do.
by the way, my english is poor. i'm not sure if you can understand my words. 
i will appreciate your suggestions,look forward your reply.

**Comment by GerardMaggiolino** [comment]
Sorry, that isn't documented. I'll update that soon. 

We use BoT-SORT's CMC files for MOT17/20, and generated DanceTrack CMC files based off their code to ensure we were testing both algorithms fairly. 

[Here's a link to BoT-SORT's CMC code. ](https://github.com/NirAharon/BoT-SORT/tree/main/VideoCameraCorrection/VideoCameraCorrection) It requires compiling OpenCV from scratch.

**Comment by upperblacksmith** [comment]
get it and thanks your reply.
