### ISSUE TITLE
SBS50

### ISSUE THREAD

**Issue by YanhuiS** [GerardMaggiolino/Deep-OC-SORT#6]
How did  you train the SBS50 model with dancetrack?  Is the weights of SBS50 on MOT17 and MOT20 from  BOT-SORT?

**Comment by GerardMaggiolino** [comment]
We found the uploaded MOT20 weights to be corrupted and re-trained them, but the MOT17 weights are from BoT-SORT directly. We followed BoT-SORT's Fast-ReID instructions to train.
